apiVersion: v1
kind: Service
metadata:
  name: app-scaling-svc
  namespace: app-scaling
spec:
  selector:
    app: app-scaling
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 8080