apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: app-scaling-cpu
  namespace: app-scaling                
spec:
  scaleTargetRef:
    apiVersion: apps/v1        
    kind: Deployment           
    name: app-scaling-dp                                                          
  minReplicaCount:  1                                      
  maxReplicaCount:  5                                                                 
  advanced:                                                      
    horizontalPodAutoscalerConfig:                          
      name: app-scaling-hpa                          
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "50"